version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - shared-pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - shared-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - shared-net

  web:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_HOST: db
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
    networks:
      - shared-net

volumes:
  shared-pgdata:
    name: shared-pgdata

networks:
  shared-net:
    name: shared-net

  # lockgen:
  #   image: ruby:3.3.0
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: bash -c "gem install bundler && bundle install"
