development:
  time_out: 7
  root_url: "https://localhost"
  transaction_return_url: "https://localhost/transactions/callback"
  admin_mail: "hello@cocociti.com"
  buffer_time_of_transaction: 1
  default_profile_pic: "https://res.cloudinary.com/cocociti/image/upload/v1449832783/default_images/profile-pic.png"
  watermark: "default_images:watermark"
  default_product_image: "https://res.cloudinary.com/cocociti/image/upload/v1449832783/default_images/default_product.png"

production:
  time_out: 7
  root_url: "https://www.cocociti.com"
  transaction_return_url: "https://www.cocociti.com/transactions/callback"
  admin_mail: "hello@cocociti.com"
  buffer_time_of_transaction: 1
  default_profile_pic: "https://res.cloudinary.com/cocociti/image/upload/v1449832783/default_images/profile-pic.png"
  watermark: "default_images:watermark"
  default_product_image: "https://res.cloudinary.com/cocociti/image/upload/v1449832783/default_images/default_product.png"
