name: Deploy to AWS Lightsail

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to AWS Lightsail
      run: |
        echo "SSH connection starting"
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Inside EC2"
          whoami
          uptime
          cd ~/wishboard
          git pull origin master
          docker compose down
          docker compose up --build -d
          echo "Deployment complete"
        EOF
